// examples/solid/src/lib/components/Card.tsx
import type { BaseComponentProps } from "@json-render/solid";

interface CardProps {
  title?: string;
  subtitle?: string;
}

export function Card(renderProps: BaseComponentProps<CardProps>) {
  return (
    <div
      style={{
        background: "#ffffff",
        "border-radius": "12px",
        border: "1px solid #e5e7eb",
        padding: "20px",
        "box-shadow": "0 1px 3px rgba(0,0,0,0.06)",
      }}
    >
      {renderProps.props.title && (
        <h2
          style={{
            "font-size": "18px",
            "font-weight": "600",
            "margin-bottom": renderProps.props.subtitle ? "4px" : "16px",
          }}
        >
          {renderProps.props.title}
        </h2>
      )}
      {renderProps.props.subtitle && (
        <p
          style={{
            "font-size": "14px",
            color: "#6b7280",
            "margin-bottom": "16px",
          }}
        >
          {renderProps.props.subtitle}
        </p>
      )}
      {renderProps.children}
    </div>
  );
}

// examples/angular/src/app/components/card.component.ts
import { Component, ViewChild, input } from "@angular/core";
import { ChildrenOutletDirective } from "@json-render/angular";

@Component({
  selector: "app-card",
  standalone: true,
  imports: [ChildrenOutletDirective],
  template: `
    <div class="card">
      @if (element().props.title; as title) {
        <h3 class="card-title">{{ title }}</h3>
      }
      @if (element().props.subtitle; as subtitle) {
        <p class="card-subtitle">{{ subtitle }}</p>
      }
      <div class="card-content">
        <ng-template jsonRenderChildren></ng-template>
      </div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
      .card {
        background: #fff;
        border-radius: 10px;
        border: 1px solid #e5e7eb;
        padding: 20px;
      }
      .card-title {
        font-size: 15px;
        font-weight: 600;
        margin-bottom: 2px;
        color: #111827;
      }
      .card-subtitle {
        font-size: 12px;
        color: #9ca3af;
        margin-bottom: 16px;
        line-height: 1.4;
      }
      .card-content {
        display: flex;
        flex-direction: column;
        gap: 12px;
      }
    `,
  ],
})
export class CardComponent {
  @ViewChild(ChildrenOutletDirective, { static: true })
  childrenOutlet!: ChildrenOutletDirective;

  readonly element = input.required<{
    props: { title?: string; subtitle?: string };
  }>();
}
