// examples/angular/src/app/components/stack.component.ts
import { Component, ViewChild, computed, input } from "@angular/core";
import { ChildrenOutletDirective } from "@json-render/angular";

@Component({
  selector: "app-stack",
  standalone: true,
  imports: [ChildrenOutletDirective],
  template: `
    <div [style]="containerStyle()">
      <ng-template jsonRenderChildren></ng-template>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
    `,
  ],
})
export class StackComponent {
  @ViewChild(ChildrenOutletDirective, { static: true })
  childrenOutlet!: ChildrenOutletDirective;

  readonly element = input.required<{
    props: {
      gap?: number;
      padding?: number;
      direction?: "vertical" | "horizontal";
      align?: "start" | "center" | "end";
    };
  }>();

  readonly containerStyle = computed(() => {
    const p = this.element().props;
    return [
      "display: flex",
      `flex-direction: ${p.direction === "horizontal" ? "row" : "column"}`,
      p.gap ? `gap: ${p.gap}px` : "",
      p.padding ? `padding: ${p.padding}px` : "",
      p.align ? `align-items: ${p.align}` : "",
      "flex-wrap: wrap",
    ]
      .filter(Boolean)
      .join("; ");
  });
}

// examples/solid/src/lib/components/Stack.tsx
import type { BaseComponentProps } from "@json-render/solid";

interface StackProps {
  gap?: number;
  padding?: number;
  direction?: "vertical" | "horizontal";
  align?: "start" | "center" | "end";
}

export function Stack(renderProps: BaseComponentProps<StackProps>) {
  return (
    <div
      style={{
        display: "flex",
        "flex-direction":
          renderProps.props.direction === "horizontal" ? "row" : "column",
        gap: renderProps.props.gap ? `${renderProps.props.gap}px` : undefined,
        padding: renderProps.props.padding
          ? `${renderProps.props.padding}px`
          : undefined,
        "align-items": renderProps.props.align,
      }}
    >
      {renderProps.children}
    </div>
  );
}
