// examples/angular/src/app/components/text.component.ts
import { Component, computed, input } from "@angular/core";

const sizeMap: Record<string, string> = {
  sm: "12px",
  md: "14px",
  lg: "18px",
  xl: "24px",
};
const weightMap: Record<string, string> = {
  normal: "400",
  medium: "500",
  bold: "700",
};

@Component({
  selector: "app-text",
  standalone: true,
  template: `<span [style]="style()">{{ text() }}</span>`,
  styles: [
    `
      :host {
        display: block;
      }
    `,
  ],
})
export class TextComponent {
  readonly element = input.required<{
    props: {
      content: unknown;
      size?: "sm" | "md" | "lg" | "xl";
      weight?: "normal" | "medium" | "bold";
      color?: string;
    };
  }>();

  readonly text = computed(() => {
    const c = this.element().props.content;
    return c == null ? "" : String(c);
  });

  readonly style = computed(() => {
    const p = this.element().props;
    return [
      `font-size: ${sizeMap[p.size ?? "md"]}`,
      `font-weight: ${weightMap[p.weight ?? "normal"]}`,
      p.color ? `color: ${p.color}` : "",
    ]
      .filter(Boolean)
      .join("; ");
  });
}

// examples/solid/src/lib/components/Text.tsx
import type { BaseComponentProps } from "@json-render/solid";

interface TextProps {
  content: string;
  size?: "sm" | "md" | "lg" | "xl";
  weight?: "normal" | "medium" | "bold";
  color?: string;
}

const sizeMap: Record<string, string> = {
  sm: "12px",
  md: "14px",
  lg: "18px",
  xl: "24px",
};

const weightMap: Record<string, string> = {
  normal: "400",
  medium: "500",
  bold: "700",
};

export function Text(renderProps: BaseComponentProps<TextProps>) {
  return (
    <span
      style={{
        "font-size": sizeMap[renderProps.props.size ?? "md"],
        "font-weight": weightMap[renderProps.props.weight ?? "normal"],
        color: renderProps.props.color,
      }}
    >
      {String(renderProps.props.content ?? "")}
    </span>
  );
}
