// examples/vite-renderers/src/solid/mount.tsx
import { render } from "solid-js/web";
import type { Spec } from "@json-render/core";
import { App } from "./App";

let dispose: (() => void) | null = null;

export function mount(container: HTMLElement, renderer: string, spec: Spec) {
  dispose = render(
    () => <App initialRenderer={renderer} spec={spec} />,
    container,
  );
}

export function unmount() {
  dispose?.();
  dispose = null;
}

// examples/vite-renderers/src/react/mount.tsx
import { createRoot, type Root } from "react-dom/client";
import type { Spec } from "@json-render/core";
import App from "./App";

let root: Root | null = null;

export function mount(container: HTMLElement, renderer: string, spec: Spec) {
  root = createRoot(container);
  root.render(<App initialRenderer={renderer} spec={spec} />);
}

export function unmount() {
  root?.unmount();
  root = null;
}
