// packages/shadcn-svelte/src/render/Stack.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { BaseComponentProps } from "@json-render/svelte";
  import type { ShadcnProps } from "../catalog.js";

  interface Props extends BaseComponentProps<ShadcnProps<"Stack">> {
    children?: Snippet;
  }

  let { props, children }: Props = $props();

  const gapMap: Record<string, string> = {
    none: "gap-0",
    sm: "gap-2",
    md: "gap-3",
    lg: "gap-4",
  };

  const alignMap: Record<string, string> = {
    start: "items-start",
    center: "items-center",
    end: "items-end",
    stretch: "items-stretch",
  };

  const justifyMap: Record<string, string> = {
    start: "",
    center: "justify-center",
    end: "justify-end",
    between: "justify-between",
    around: "justify-around",
  };
</script>

<div
  class={`flex ${props.direction === "horizontal" ? "flex-row flex-wrap" : "flex-col"} ${gapMap[props.gap ?? "md"] ?? "gap-3"} ${alignMap[props.align ?? "start"] ?? "items-start"} ${justifyMap[props.justify ?? "start"] ?? ""}`}
>
  {@render children?.()}
</div>

// apps/web/components/demo/stack.tsx
"use client";

import type { ComponentRenderProps } from "./types";
import { baseClass, getCustomClass } from "./utils";

export function Stack({ element, children }: ComponentRenderProps) {
  const { props } = element;
  const customClass = getCustomClass(props);
  const isHorizontal = props.direction === "horizontal";

  const gapClass =
    props.gap === "lg"
      ? "gap-3"
      : props.gap === "md"
        ? "gap-2"
        : props.gap === "sm"
          ? "gap-1"
          : props.gap === "none"
            ? "gap-0"
            : "gap-2";

  const alignClass =
    props.align === "center"
      ? "items-center"
      : props.align === "end"
        ? "items-end"
        : props.align === "stretch"
          ? "items-stretch"
          : "items-start";

  const justifyClass =
    props.justify === "center"
      ? "justify-center"
      : props.justify === "end"
        ? "justify-end"
        : props.justify === "between"
          ? "justify-between"
          : props.justify === "around"
            ? "justify-around"
            : "";

  return (
    <div
      className={`flex ${isHorizontal ? "flex-row flex-wrap" : "flex-col"} ${gapClass} ${alignClass} ${justifyClass} ${baseClass} ${customClass}`}
    >
      {children}
    </div>
  );
}
