// examples/vue/src/App.vue
<script setup lang="ts">
import { StateProvider } from "@json-render/vue";
import { demoSpec } from "./lib/spec";
import DemoRenderer from "./DemoRenderer.vue";

const initialState = demoSpec.state ?? {};
</script>

<template>
  <!-- StateProvider sets up the reactive state store for the whole tree -->
  <StateProvider :initial-state="initialState">
    <DemoRenderer />
  </StateProvider>
</template>

// examples/solid/src/App.tsx
import { StateProvider } from "@json-render/solid";
import { demoSpec } from "./lib/spec";
import { DemoRenderer } from "./DemoRenderer";

export function App() {
  const initialState = demoSpec.state ?? {};

  return (
    <StateProvider initialState={initialState}>
      <DemoRenderer />
    </StateProvider>
  );
}
